spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: docker
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
