spring:
  main:
    web-application-type: reactive
  data:
    mongodb:
      database: reactive_webflux
      host: localhost
      username: mongo
      password: pass
      authentication-database: admin
